[spins.lxqt.x86_64]
fas = [ "lupinix", "zsun" ]
maintainers = [ "Christian Dersch", "Zamir SUN" ]
[spins.lxqt.armhfp]
fas = [ "lupinix", "zsun" ]
maintainers = [ "Christian Dersch", "Zamir SUN" ]

[spins.xfce.x86_64]
fas = [ "nonamedotc", "kevin", "maxamillion" ]
maintainers = [ "Mukundan Ragavan", "Kevin Fenzi", "Adam Miller" ]
[spins.xfce.armhfp]
fas = [ "nonamedotc", "kevin", "maxamillion" ]
maintainers = [ "Mukundan Ragavan", "Kevin Fenzi", "Adam Miller" ]

[spins.kde.x86_64]
fas = [ "rdieter", "marcdeop", "ngompa" ]
maintainers = [ "Rex Dieter", "Marc Deop", "Neal Gompa" ]

[spins.cinnamon.x86_64]
fas = [ "grinnz" ]
maintainers = [ "Dan Book" ]

[spins.lxde.x86_64]
fas = [ "cwickert", "mtasaka" ]
maintainers = [ "Christoph Wickert", "Mamoru TASAKA" ]
[spins.lxde.armhfp]
fas = [ "cwickert", "mtasaka" ]
maintainers = [ "Christoph Wickert", "Mamoru TASAKA" ]

[spins.soas.x86_64]
fas = [ "chimosky", "aperezbios" ]
maintainers = [ "Chihurumnaya Ibiam", "Alex Perez" ]
[spins.soas.armhfp]
fas = [ "chimosky", "aperezbios", ]
maintainers = [ "Chihurumnaya Ibiam", "Alex Perez" ]

[labs.astronomy_kde.x86_64]
fas = [ "lupinix" ]
maintainers = [ "Christian Dersch" ]

[labs.security.x86_64]
fas = [ "fab", "jsimon", "q5sys"]
maintainers = [ "Fabian Affolter", "Joerg Simon", "JT Pennington" ]

[labs.comp_neuro.x86_64]
fas = [ "bt0dotninja", "dan1mal", "ankursinha", "neuro-sig" ]
maintainers = [ "Alberto Rodriguez Sanchez", "Danny Lee", "Ankur Sinha", "NeuroFedora SIG" ]

[labs.design_suite.x86_64]
fas = [ "luya" ]
maintainers = [ "Luya Tshimbalanga" ]

[labs.games.x86_64]
fas = [ "dagostinelli", "richardanaya" ]
maintainers = [ "Darryl T. Agostinelli", "Richard Anaya" ]

[labs.jam_kde.x86_64]
fas = [ "q5sys" ]
maintainers = [ "JT Pennington" ]

[labs.python_classroom.x86_64]
fas = [ "churchyard", "python-sig" ]
maintainers = [ "Miro Hrončok", "Python SIG" ]

[labs.scientific_kde.x86_64]
fas = [ "scitech" ]
maintainers = [ "SciTech SIG" ]

[labs.scientific.x86_64]
fas = [ "scitech" ]
maintainers = [ "SciTech SIG" ]

[labs.robotics.x86_64]
fas = [ "x3mboy", "robotics-sig" ]
maintainers = [ "Eduard Lucena", "Robotics SIG" ]

[spins.i3.x86_64]
fas = [ "jflory7", "defolos", "nasirhm", "odilhao", "x3mboy" ]
maintainers = [ "Justin Flory", "Dan Čermák", "Nasir Hussain", "Odilon Junior", "Eduard Lucena" ]

[eln]
fas = [ "sgallagh", "tdawson", "asamalik" ]
maintainers = [ "Stephen Gallagher", "Troy Dawson", "Adam Samalik" ]

[spins.budgie.x86_64]
fas = [ "joshstrobl" ]
maintainers = [ "Joshua Strobl" ]

[spins.sway.x86_64]
fas = [ "alebastr", "jkonecny", "anthr76", "fale" ]
maintainers = [ "Aleksei Bavshin", "Jiří Konečný", "Anthony Rabbito", "Fabio Alessandro Locati" ]

[silverblue.x86_64]
fas = [ "siosm", "tpopela" ]
maintainers = [ "Timothée Ravier", "Tomáš Popela" ]
[silverblue.aarch64]
fas = [ "siosm", "tpopela" ]
maintainers = [ "Timothée Ravier", "Tomáš Popela" ]
[silverblue.ppc64le]
fas = [ "siosm", "tpopela" ]
maintainers = [ "Timothée Ravier", "Tomáš Popela" ]

[kinoite.x86_64]
fas = [ "siosm" ]
maintainers = [ "Timothée Ravier" ]
[kinoite.aarch64]
fas = [ "siosm" ]
maintainers = [ "Timothée Ravier" ]
[kinoite.ppc64le]
fas = [ "siosm" ]
maintainers = [ "Timothée Ravier" ]

[sericea.x86_64]
fas = [ "alebastr", "jkonecny", "anthr76", "fale" ]
maintainers = [ "Aleksei Bavshin", "Jiří Konečný", "Anthony Rabbito", "Fabio Alessandro Locati" ]
[sericea.aarch64]
fas = [ "alebastr", "jkonecny", "anthr76", "fale" ]
maintainers = [ "Aleksei Bavshin", "Jiří Konečný", "Anthony Rabbito", "Fabio Alessandro Locati" ]
[sericea.ppc64le]
fas = [ "alebastr", "jkonecny", "anthr76", "fale" ]
maintainers = [ "Aleksei Bavshin", "Jiří Konečný", "Anthony Rabbito", "Fabio Alessandro Locati" ]

[onyx.x86_64]
fas = [ "joshstrobl" ]
maintainers = [ "Joshua Strobl" ]
[onyx.aarch64]
fas = [ "joshstrobl" ]
maintainers = [ "Joshua Strobl" ]
[onyx.ppc64le]
fas = [ "joshstrobl" ]
maintainers = [ "Joshua Strobl" ]
